# Generated by Django 4.1.4 on 2022-12-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(),
        ),
    ]
